### ISSUE TITLE
pip install error (Double requirement given: tqdm)

### ISSUE THREAD

**Issue by RandomPrototypes** [megvii-research/CoNR#1]
Hello,
the requirements.txt contains 2 times tqdm, and it causes an error

> ERROR: Double requirement given: tqdm (from -r requirements.txt (line 10)) (already in tqdm>=4.35.0 (from -r requirements.txt (line 3)), name='tqdm')

removing the last tqdm solves the problem

**Comment by P2Oileen** [comment]
Thank you for this issue, the problem fixed
