### ISSUE TITLE
在使用colab的时候无法跑通

### ISSUE THREAD

**Issue by yicheng921** [megvii-research/CoNR#11]
![代码截图](https://user-images.githubusercontent.com/125963129/220302471-ebb58176-19c2-46f7-9081-facb2e9c1eda.jpg)
在多次尝试之后，每一次到这一步都会报错。
提示需要大概40分钟，但是无法中止来获得片段。最终的图片和视频都无法生成。
期待您的解答

**Comment by transpchan** [comment]
抱歉，由于部分作者只对水文章感兴趣，v1已经没人维护了。建议改用 https://github.com/transpchan/Live3D-v2
。
