### ISSUE TITLE
Alternative models for UDP detector

### ISSUE THREAD

**Issue by aartykov** [megvii-research/CoNR#14]
Hi. First of all thanks for the great work. Could you, please,  suggest several alternative models for UDP detection?
Thanks in advance.

**Comment by aartykov** [comment]
Also, is the provided UDP model only works well with anime images?

**Comment by P2Oileen** [comment]
Hi, aartykov! Thank you for your attention to this work. In our CoNR, only ONE pretrained weight of UDP detector is provided, and there are no other models. Also, our scope of work only includes animated characters, but you can try to inference with other kinds of images as input, and you are more than welcome to share your results with us.
