### ISSUE TITLE
Typo for Streamlit?

### ISSUE THREAD

**Issue by bycloudai** [megvii-research/CoNR#2]
Hi, thank you for sharing your amazing work!

The command you instructed here https://github.com/megvii-research/CoNR#run
Says ```streamlit run streamlit.py --server_port=8501```
but I got it running with ```streamlit run streamlit.py --server.port=8501```

Is this potentially a typo? Thanks!

**Comment by P2Oileen** [comment]
Thank you for this issue, I did make a typo. Fixed yet
