### ISSUE TITLE
如何得到一张图片的UDP？

### ISSUE THREAD

**Issue by baojunshan** [megvii-research/CoNR#4]
您好，如果我有一张背景透明的png图片，该如何得到他的UDP图像呢？

**Comment by transpchan** [comment]
See #3 and https://transpchan.github.io/live3d

**Comment by P2Oileen** [comment]
你好 Senders！
您可以使用UDP检测器，这是一个从图片中获取UDP的神经网络，我们提供了相应的代码和权重。
你需要将这张图片放到姿势文件夹下，然后在推理时，使用如下的指令：
```
python -m torch.distributed.launch \
--nproc_per_node=1 train.py --mode=test \
--world_size=1 --dataloaders=2 \
--test_input_poses_images={dir_to_poses} \ # 将这里的路径填写为，你的图像所在的姿势文件夹
--test_input_person_images={dir_to_character_sheet} \
--test_output_dir={dir_to_save_result} \
--test_checkpoint_dir={dir_to_weights} \
--test_pose_use_parser_udp=True  \
--test_output_udp=True
```
在执行结束后，你会在 {dir_to_save_result} 的文件夹下找到两张图片；一张是推理的结果，一张是UDP检测器的结果。如[这个issue下的回复](https://github.com/megvii-research/CoNR/issues/3#issuecomment-1201394534)

如果还有任何问题，欢迎继续跟我们沟通～

**Comment by baojunshan** [comment]
> See #3 and https://transpchan.github.io/live3d

你好，感谢回复，我是用code下面的代码
```
 python -m torch.distributed.launch --nproc_per_node=1 train.py --mode=test --world_size=1 --dataloaders=2  --test_input_poses_images=../../CoNR/data/poses/short_hair --test_input_person_images=../../CoNR/data/short_hair_images/ --test_output_dir=../../CoNR/data/output --test_checkpoint_dir=../../CoNR/weights --test_pose_use_parser_udp=True --test_output_udp=True
```
其中poses/short_hair里是一些二进制的pose，short_hair_images里是4张输入图片，运行下来会报如下错误
```
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch-1.8/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/pytorch-1.8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/pytorch-1.8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/baojunshan/Live3D/code/data_loader.py", line 247, in __getitem__
    target = self.get_gt_from_disk(
  File "/home/baojunshan/Live3D/code/data_loader.py", line 236, in get_gt_from_disk
    assert (sample["mask"].dtype == torch.uint8)
AssertionError
```
我尝试强转uint8，得到的最终结果很奇怪

**Comment by P2Oileen** [comment]
你好 Senders！
我看到了您使用
```
--test_pose_use_parser_udp=True --test_output_udp=True
```
这样的选项会用于从`test_input_poses_images`文件夹下的图片中提取姿态UDP并输出。如果你需要提取图片的UDP，在`test_input_poses_images`应该输入需要推理出UDP的图片的所在位置；然而看起来您不是这样做的
> 其中poses/short_hair里是一些二进制的pose

我不确定您的`二进制pose`是否为png图片，猜测这是导致问题的原因

**Comment by baojunshan** [comment]
> 你好 Senders！ 我看到了您使用
> 
> ```
> --test_pose_use_parser_udp=True --test_output_udp=True
> ```
> 
> 这样的选项会用于从`test_input_poses_images`文件夹下的图片中提取姿态UDP并输出。如果你需要提取图片的UDP，在`test_input_poses_images`应该输入需要推理出UDP的图片的所在位置；然而看起来您不是这样做的
> 
> > 其中poses/short_hair里是一些二进制的pose
> 
> 我不确定您的`二进制pose`是否为png图片，猜测这是导致问题的原因

感谢，跑成功了。

我还有一个疑问，在readme中
```
mkdir {dir_to_save_result}

python -m torch.distributed.launch \
--nproc_per_node=1 train.py --mode=test \
--world_size=1 --dataloaders=2 \
--test_input_poses_images={dir_to_poses} \
--test_input_person_images={dir_to_character_sheet} \
--test_output_dir={dir_to_save_result} \
--test_checkpoint_dir={dir_to_weights}

ffmpeg -r 30 -y -i {dir_to_save_result}/%d.png -r 30 -c:v libx264 output.mp4 -r 30
```
`dir_to_poses` 是指 `Ultra-Dense Pose sequences for two characters.`这个吗？
我的理解这是3D的UDP动作序列，然后结合`--test_input_person_images`这个输入不同视角的动漫人物，预测出类似3D点云的结果，再投影回2D平面得到最终结果，是这样吗？我不太理解这两个输入参数`--test_input_poses_images`， `--test_input_person_images`的含义。

**Comment by P2Oileen** [comment]
很抱歉`test_input_poses_images`中包含images这个单词，可能会导致一些歧义，我重新给出这些parser的准确说明：

`--test_input_poses_images` 是**姿势**的输入文件夹，姿势可以是UDP序列，也可以是图片；如果是前者，使用我们README中的标准运行方式就可以；如果是后者，就需要同时打开这个开关：`--test_pose_use_parser_udp=True`，以从图片中提取UDP，再输入到CoNR中。

`--test_input_person_images` 是我们论文中提到的Character Sheets的文件夹，就是手绘人设图的文件夹。

**Comment by baojunshan** [comment]
非常感谢您的回复，这是一个很棒的工作。
