### ISSUE TITLE
could you share the training data？

### ISSUE THREAD

**Issue by ForrestPi** [megvii-research/CoNR#8]
Hi，interesting work! could you release the training data？

**Comment by transpchan** [comment]
See https://github.com/transpchan/Live3D/issues/1

**Comment by transpchan** [comment]
Hi, you can try to build your own datasets at the moment (See https://github.com/transpchan/Live3D/issues/1)

This project and dataset was criticized as useless by our reviewers. If you like this project, you could help us by sharing it on social media. If the project become popular enough, the other authors might stop trying their luck on the next venue and release the dataset.

**Comment by P2Oileen** [comment]
I'm sorry for just sawing this issue😢, thank you for your interest! 
We responsibly declared in the paper that the dataset would be open-sourced, but it's still under organization to avoid possible problems. If you wish to build your own dataset, you can use [MMD2UDP](https://github.com/KurisuMakise004/MMD2UDP) to build your own image-UDP pairs.
We also sincerely hope that CoNR can be fully reproduced as soon as possible, so please wait for our good news! 💗
