### ISSUE TITLE
通过输入一个视频（已经扣出人物）的图片序列，然后让算法自动得到UDP发现最后的效果图片不稳定

### ISSUE THREAD

**Issue by hl123-123** [megvii-research/CoNR#9]
我看了已经close的issue，发现你们是使用另一种使用3D模型的方法得到UDP，这种方法应该会效果更好吧

**Comment by transpchan** [comment]
这一版放出来的UDP检测器精度不是很高，我们在做v2了，UDP检测器的性能会有提升。

**Comment by transpchan** [comment]
也许。。。能提供一些图么？如果贴不下可以发到:transpchan@gmail.com

这一版放出来的UDP检测器精度不是很高，下一版（v2）的UDP检测器的性能应该会有提升。
